name: Health Check

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  healt_check_job:
    runs on: ubuntu-18.04
    steps:
      - name: Health Check
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://toxpuropokedex.herokuapp.com/health