name: Health Check

on:
  push:
    branches:
      - master
  #schedule:
  # - cron: '*/1 * * * *'
  # Scheluding worked but I comment it out in order not to use all dyno time
jobs:
  healt_check_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Health Check
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://toxpuropokedex.herokuapp.com/health